src/App.jsx, src/main.jsx, src/styles/Variables.jsx
```js
function App() {
return (
<>
<Reset />
<Variables />
<GlobalStyle />
<Router />
</>
);
}
export default App;
```
```js
createRoot(document.getElementById("root")).render(
<StrictMode>
<Reset />
<Variables />
<App />
</StrictMode>
);
```
```css
/* font-size */
--font-size-12: 12px;
--font-size-14: 14px;
--font-size-15: 15px;
--font-size-16: 16px;
--font-size-18: 18px;
--font-size-20: 20px;
--font-size-24: 24px;
--font-size-28: 28px;
/* font-weight */
--font-weight-regular: 400;
--font-weight-medium: 500;
--font-weight-bold: 700;
```
=> style: 전역 스타일 구조 및 변수 최적화및 폰트 관련 변수 추가

src/components/Badge.jsx, src/components/Badge/Badge.jsx, src/components/Badge/EmojiBadge.jsx, src/pages/Main/components/test.jsx, src/styles/Variables.jsx
일단 간단하게 아이콘만 구현해놓았습니다 popOver 상태관리나 부가적인 건 Dropdown 커스텀 훅을 생성후 이를통해 관리하도록 만들어보겠습니다!
- [ x ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ x ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> Feature: Badge, EmojiBadge

src/components/Badge/EmojiBadge.jsx, src/components/Dropdown/Dropdown.jsx, src/components/Dropdown/ReactionBadges.jsx, src/components/Dropdown/useDropdown.jsx, src/pages/List/ListPageHeader.jsx, src/pages/Main/components/MainPage.jsx, src/pages/Main/components/test.jsx
Dropdown 컴포넌트에서 기능만 추출해 useDropdown 커스텀 훅을 만들었습니다.
만든 커스텀 훅에서 일부 기능과 Badges를 이용해 ReactionBadges를 만들었습니다.
현재 목데이터 사용중입니다.
ListPageHeader에도 적용시켜놓았습니다.
ReactionBadges는 반응형에 따라 동작하고 ReadOnly입니다, count가 높은 순 정렬하였습니다. 
추후에 api를 추가하고 여유가 있다면 무한스크롤도 적용시키고싶습니다.
메모리 누수관련해서 낭비되는 부분이 없는지 좀 더 최적화할 방안은 없는지 봐주셨으면 좋겠습니다!
https://github.com/user-attachments/assets/0957c43a-3e3a-4ab7-a6e8-ac9f016754a9
- [ x ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ x ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> Feature dropdown custom hook

src/components/MessageCard/MessageCard.jsx, src/components/Modal/MessageCardModal.jsx, src/components/Modal/Modal.jsx
- MessageCard 자체의 반응형 줄바꿈 스타일과 Modal 안에서의 MessageCard 반응형 줄바꿈이 다르게 처리되도록 클램핑 스타일 분리
- MessageCard.Profile/Content/CreatedAt의 Styles를 배열 ➡️ 함수 조합 형태로 수정
=> Style: Modal, MessageCard 클램핑 스타일 반응형 수정

src/components/Dropdown/Dropdown.jsx
=> Style(Dropdown): 드롭다운 항목 커서 pointer 추가

src/pages/List/ListPageHeader.jsx
이모지 팝오버 리스트페이지 헤더에 적용 및 위치조정 (li태그에 함께있는 요소의 높이가 달라서 단차가 생기던 문제)
=> Style: ? ListPageHeader에 EmojiPopover 적용 및 위치조정

src/api/get/getProfileImages.js, src/api/useFetch.js, src/pages/Post/PostMessage/SelectProfileImage.jsx
- api로 프로필 이미지 불러오기
- 이미지 선택 시 기본 아바타를 선택된 이미지로 변경
- api 연동할 때 공통으로 쓰일 수 있는 `useFetch` 훅을 생성해서 프로필 이미지 로드
=> Feature: 메시지 작성 페이지 - 프로필 이미지 선택 컴포넌트(SelectProfileImage) 생성, useFetch 훅 생성 및 적용

src/api/ReactionApi.js
=> Feature reaction api

src/components/Form/Input/Input.jsx, src/pages/Post/PostMessage/PostMessagePage.jsx
- 메시지 작성 페이지(`PostMessagePage`)에서 이름, 메시지 내용란을 작성하지 않으면 `생성하기` 버튼 비활성화
- 유효성 검사 스타일 잡기 위해 Input 컴포넌트 수정
- QA용 PR이므로 셀프 머지하겠습니다.
- QA 이후 메시지 내용란 유효성 검사 UI도 추가해야 될 것 같습니다.
=> Feature: 메시지 작성 페이지 - 폼 유효성 검사 구현

src/api/ReactionApi.js, src/components/Badge/EmojiBadge.jsx, src/components/Dropdown/EmojiPopover.jsx, src/components/Dropdown/ReactionBadges.jsx, src/components/Dropdown/useDropdown.jsx, src/components/Header/ReactionBox.jsx, src/pages/List/ListPageHeader.jsx
같은 브랜치에서 잡업해서 작업내용이 병합되었습니다 죄송합니다,,,
ReactionApi 를 객체형태로 get과 post를 생성하여 사용하도록 하였습니다.
제가 api를 다루는 데에 너무 미숙해서 시간이 너무 오래걸리고말았네요
EmojiPopover에서는 post, ReactionBadges에서는 get을 사용하는데 둘의 실시간 연동을 위해 하나의 컴포넌트로 묶어서 상태를 공유하게 했습니다.
QA체크시트에 있던 요구사항도 적용해놨습니다!
약속 나가기 전에 최대한 마무리하려했는데 너무 늦어져서 퀄리티가 좀 떨어지는 것 같습니다..확인하긴 했지만 급하게 수정해서 제대로 했는지 모르겠습니다 죄송합니다,,
api연동후 테스트까지 진행하긴 했는데 진선님이 만드신 id말고 이외에서는 제가따로 id를 생성하지 않아서 오류가 나더라고요 그래서 11723에서 테스트를 해봤습니다.. 되긴 했는데 배포시엔 어떻게 동작할지 모르겠어서 api관련 부분 리뷰주시면 감사하겠습니다!
https://github.com/user-attachments/assets/31292d5c-fd84-48b0-bd67-32f9a44d3221
=> feat: ReactionsApi 연동 

src/pages/List/PostIdPageHeader.jsx, src/pages/Post/PostDetail/MessagesPage.jsx, src/pages/StyleGuide/StyleGuidePage.jsx, src/utils/useWindowWidth.jsx
반응형으로 모바일 사이즈에서 헤더가 두 줄로 분리되는 부분 추가, 요소사이 데코레이션(?)세로줄 수정, 글로벌헤더 조건부렌더링으로 모바일사이즈에서는 렌더링x
진선님 pr도 있고 머지하게되면 충돌이 좀 있을것 같습니다 그 부분은 다른 분들 코드에 영향안가게 제 코드를 수정하는쪽으로 무조건 맞춰서 머지하도록하겠습니다!
https://github.com/user-attachments/assets/b94c6e64-7823-4829-b7a5-1856939edaa1
- [ x ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ x ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> [1차 QA반영] Style:  postIdPage header

src/components/Dropdown/EmojiPopover.jsx
- [ x ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ x ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> Style: EmojiPopover 오타수정 (이모지 선택시 close함수 실행인데 ()를 안붙여서 호출이 안됐음)

package-lock.json, src/api.jsx, src/components/Form/Input/Input.jsx, src/pages/Post/PostCreatePage.jsx, src/pages/Post/components/SeletBackground.jsx
- input focus border가 안 쪽에 배치되는 거 수정 (div 말고 input에 padding 주기)
- ‘값을 입력해 주세요’ 메세지가 나타날 때 아래 레이아웃이 밀림. 미리 높이를 잡아두기.
- 페이지 하단 여백 추가 필요
- input의 최대 입력값 제한이 필요
- autofocus 추가 고려 
- 컬러-이미지 탭버튼 전환 시 Layout Shift 방지 필요
Color Option 하드코딩으로 4가지 색 나오게까지 만들었습니다!
- Color Option 만들면서 UI적으로 코드를 조금 수정하였습니다. 
Input 컴포넌트에 직접적으로 코드 수정을 했는데 한 번 확인해 주시면 감사하겠습니다.
- [ X ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ X ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> [1차 QA 반영] 롤링페이퍼 생성 페이지 (/post)

src/components/Dropdown/Dropdown.jsx, src/pages/Post/PostMessage/PostMessagePage.jsx
- 메시지 작성 시 드롭다운 항목 선택하면 폼 제출되는 현상 수정
- 메시지 생성하기 버튼 클릭 시 해당 롤링페이퍼 페이지로 이동 (요구사항 구현)
=> Fix(PostMessagePage): 메시지 작성 시 드롭다운 항목 선택하면 폼 제출되는 현상 수정

src/pages/Main/components/MainPage.jsx
- 메인 페이지 반응형 여백 수정
- '롤링페이퍼 만들기' 버튼 width, height 크기 auto 처리 (padding으로만 영역 잡기)
=> Style: 메인 페이지 퍼블리싱 마감

src/components/Avatar/AvatarList.jsx, src/components/Badge/Badge.jsx, src/components/MessageCard/AddMessageCardButton.jsx, src/components/MessageCard/MessageCard.jsx, src/components/MessageCard/MessageCardStyle.js, src/components/Modal/ModalContainer.jsx, src/pages/List/PostIdPageHeader.jsx, src/pages/Post/PostDetail/MessageActionButtons.jsx, src/pages/Post/PostDetail/MessagesPage.jsx
- 페이지 레이아웃 반응형 
- 배경색 데이터와 디자인 변수 매핑 (`beige: 'var(--beige-200)'`)
- 메시지 카드 관계에 Badge 컴포넌트 적용
=> Style: 롤링페이퍼 페이지(MessagesPage) 퍼블리싱

src/components/Header/GlobalHeader.jsx, src/styles/Variables.jsx
수정하면서 padding이 맞지않는 문제가 발생해 variables의 Header부분 수정
=> Style: GlobalHeader z-index: 999 , height: 64px 로 수정

src/components/Header/GlobalHeader.jsx
=> style: globalHeader z-index 원복

src/components/Dropdown/EmojiPopover.jsx, src/components/Dropdown/ReactionBadges.jsx
비어있는 드롭다운을 방지하기 위해 Reaction이 존재할 경우에만 토글되도록 수정
=> refactor: ReactionBadges가 Reaction이 존재할 경우에만 토글 가능하게 수정

src/components/Header/GlobalHeader.jsx
- `/post/{id}` 페이지에서 로고 가운데 정렬
=> Style: 글로벌 헤더 64px에 맞춰 세로 정렬

src/components/Skeleton/SkeletonImage.jsx, src/pages/Post/components/SelectBackground.jsx
- 이미지 로드 완료 여부에 따라 `img` 또는 `Skeleton`을 리턴하는 `SkeletonImage` 컴포넌트를 생성
-  롤링페이퍼 생성 페이지 이미지 탭에 `Suspense`로 `SkeletonImage` 적용
=> Feature: SelectBackground에 Suspense로 스켈레톤 구현

src/components/Header/GlobalHeader.jsx
=> Style: 글로벌 헤더 반응형 수정

src/components/Avatar/Avatar.jsx, src/pages/Post/hooks/useInfiniteMessages.js
Avatar컴포넌트의 프로파일 이미지에 스켈레톤 추가하였습니다.
=> Feat/post detail/profile skeleton

src/App.jsx, src/hooks/usePageLoadTransition.js, src/pages/LoadingPage.jsx
- 사이트 진입 시, 또는 새로고침 시 간단한 로딩 UI 표시
- 로드 완료되면 페이지 fadeIn 트랜지션 처리
- `App` 컴포넌트에 적용
- 코드 복잡해지지 않게 관련 로직 `usePageLoadTransition` 훅으로 분리
https://github.com/user-attachments/assets/75731462-e526-4d16-a611-99a4f08d1d6b
=> Feature: 페이지 로딩 UI 및 트랜지션 추가

src/pages/Post/PostDetail/MessageActionButtons.jsx
=> 토스트 기능 상세페이지에 추가

src/hooks/useGetScrollTopPos.js, src/pages/List/PostIdPageHeader.jsx
- 별 차이는 없는데 헤더에 그림자가 있으면 본문이랑 구분이 더 잘 되어서 추가해봤습니다
- 일정 스크롤 이상 내려갔을 때만 그림자 적용
=> Style: 롤링페이퍼 페이지에서 스크롤 내리면 헤더에 그림자 추가

src/components/Button/AddEmojiButton.jsx, src/pages/Post/PostDetail/PostDetailPage.jsx
=> style: PostIdPageHeader 반응형 오차 대비 하드코딩으로 수정

src/pages/Post/PostMessage/PostMessagePage.jsx, src/styles/Reset.jsx
=> Feature: 메시지 작성 페이지 '뒤로가기' 버튼 추가

src/components/MessageCard/AddMessageCardButton.jsx, src/pages/Post/PostDetail/MessagesPage.jsx, src/pages/Post/PostDetail/PostDetailPage.jsx
스크롤시 배경화면 확대 오류 해결,메시지 작성 이동 버튼에 힌트 텍스트 추가
=> fix:스크롤시 배경화면 확대 오류 해결,메시지 작성 이동 버튼에 힌트 텍스트 추가

src/components/Button/ScrollToTopButton.jsx, src/pages/Post/PostDetail/MessagesPage.jsx
맨 위로 스크롤 해 주는 버튼 추가
등록되지 않은 사용자일 때 토스트롤도 알림
=> Feat/post detail/button

src/pages/Main/components/MainPage.jsx
- 메인 페이지가 심심해서 섹션과 하단 버튼에 애니메이션을 넣었습니다
=> Feat/main page 애니메이션 추가

package-lock.json, src/components/MessageCard/MessageCard.jsx, src/pages/Post/hooks/useMessagesPage.js
기존의 휴지통 버튼이 기획이 바뀌면서 아무 기능도 하지 않게 되어서 클릭했을 경우에 개별 삭제가 가능하도록 기능을 추가하였습니다.
=> feat: 개별 삭제 버튼

src/pages/Post/PostMessage/PostMessagePage.jsx
=> fix(PostMessagePage): 프로필 기본 이미지 state 기본값 경로 수정

src/pages/Post/PostMessage/PostMessagePage.jsx
Reverts Team-07-Project/Team-07-Project#147
=> Revert "fix(PostMessagePage): 프로필 기본 이미지 state 기본값 경로 수정"

src/components/Dropdown/ReactionBadges.jsx
=> refactor: ReactionBadges position 문제 해결

index.html
=> feat: 모바일에서 화면 확대 방지 (user-scalable=no)

src/pages/Post/PostMessage/SelectProfileImage.jsx
=> Refactor(SelectProfileImage): 프로필 이미지 로드 방식 Suspense로 변경
